### ISSUE TITLE
HomeKit notification when last person go out

### ISSUE THREAD

**Issue by Cavech84** [MiguelRipoll23/homebridge-securitysystem#101]
Is there way to automate alarm arm when the last person go out of the home without confirmation? Now the notification tell me confirmation to do that.
Thanks for this plug in.

**Comment by MiguelRipoll23** [comment]
Hey there,

Yup! Go to the plugin settings and enable the `Show Mode Switches` that you can find under the switches section, then edit the automation that you're currently using to turn on any of these mode switches that will appear instead. Otherwise it will result in a confirmation due to security limitations from Apple.

**Comment by Cavech84** [comment]
Thanks a lot for your quick answer. This plug in is amazing 👍🏻
