### ISSUE TITLE
Home control needs access to lockscreen

### ISSUE THREAD

**Issue by Multisaft7** [MiguelRipoll23/homebridge-securitysystem#132]
Hey...I wanted to use your plugin? But I have got one question...?!
Why does the app need access to my home control on my lockscreen when my iPhone is locked?

**Comment by MiguelRipoll23** [comment]
Hey there,

Sorry, I’m a little bit confused… which app?
Can you provide further details or a screenshot?

**Comment by Multisaft7** [comment]
I disabled the home kit control in the notificationcenter that when my iPhone is locked so nobody can open my door or something else when my iPhone is locked...

But when I want to setup an automation for the security system HomeKit told me to activate the lockscreen control for HomeKit

![image](https://user-images.githubusercontent.com/33881175/121823660-02973200-cca7-11eb-90e6-0c0cbc398b1f.png)![image](https://user-images.githubusercontent.com/33881175/121823656-fc08ba80-cca6-11eb-85cf-d3448a9658ae.png)

**Comment by MiguelRipoll23** [comment]
Oh, I see.

That behavior is coming from iOS, it's weird because even if you enable Home Control it will ask you to unlock anyways due to their strict security.

Anyways, go to the plugin settings and enable the option `Show Mode Switches` that you can find in the switches section. This will show some switches you can turn on and will set your security system to other mode via automations bypassing Apple's rules.

Hope it helps.

**Comment by Multisaft7** [comment]
So without the switches it will always ask me before doing my automation, right?!![image](https://user-images.githubusercontent.com/33881175/123330325-2c214a80-d53e-11eb-8123-9038f1ac795b.jpeg)
Or can I avoid these question?

**Comment by MiguelRipoll23** [comment]
Exactly, you need the switches due to security limitations made by Apple to prevent malicious actions.
