### ISSUE TITLE
Sensor trigger multiple times

### ISSUE THREAD

**Issue by Deshmir** [MiguelRipoll23/homebridge-securitysystem#166]
### Plugin version

6.0.3

### Plugin configuration

Both motion sensor triggers on 3 seconds

### Homebridge version

1.3.4

### What's your question?

With iOs 15 the multiple trigger doesnt work as in 14.x.

With 14.x multiple notifications were created for each trigger, until you turned it off.

With 15.0 only the first trigger creates a notification, and the following ones dont. I do see the motion sensor going on and off in Home.

Is it something that can be fixed in the plugin, or do I have to search in Home itself?

**Comment by MiguelRipoll23** [comment]
Hey there,

I've tested it on my iPhone 11 and iPad Air 2020 both running on iOS/iPadOS 15 and seems to work correctly, multiple notifications are received. Using HomePod Mini as Home Hub.

Maybe you have your motion sensor notifications disabled and you're just seeing the critical notification that comes from the security system instead of the following ones that come from the motion sensor? Otherwise check if your Home Hub connectivity is alright.

**Comment by Deshmir** [comment]
Thanks for the response!

I did mess around with the notifications, and it works now.
This morning the alarm just kept going off with notifications untill I turned it off!
