### ISSUE TITLE
Allow string as server auth code or allow server API to be read only

### ISSUE THREAD

**Issue by alexh-name** [MiguelRipoll23/homebridge-securitysystem#199]
### What are you missing?

Hi!

I'd like to check the status of the plugin via the API. However I was wondering if there is a particular reason that the auth code is expected to be an int? (https://github.com/MiguelRipoll23/homebridge-securitysystem/blob/stable/src/index.js#L1044)

I'd like to make sure that I don't unnecessarily allow easy change of the plugins state just to be able to check it's status. Ideally I could set the API read only, or at least make the auth key a long random string.

Thanks for the plugin!

**Comment by MiguelRipoll23** [comment]
Hey there,

When I initially was thinking about how to to implement the API security I came to the conclusion that making it more secure wasn't worth it.

The API is behind a non-secure HTTP server, that means that is possible to intercept any credentials being sent, even if I moved it to HTTPS it would be useless due to the certificate being self-signed. Adding a encryption and validation layer would limit support so that's why it ended up being a simple PIN code.

I can allow a string to be sent too if you prefer though.
