### ISSUE TITLE
logic for elgato eve siren

### ISSUE THREAD

**Issue by Karrypto** [MiguelRipoll23/homebridge-securitysystem#2]
I need help configuring the alarm logic in the Eve app. I have a 240V siren connected via Eve Energy plug. How do i use the security system siren switch properly? How can I logically combine these two switches?

**Comment by MiguelRipoll23** [comment]
Hello, sorry for the delay!

The Siren switch that appears using this plugin is merely used to trigger the security system using a HomeKit accessory as that isn't currently possible with a real accessory.

Combining them isn't an option due to the reason above, you can use the `An Accessory is Controlled` trigger from the Home app to turn on your Eve Energy if the virtual switch state is on. That way you can also be able to control your accessories based on the `Triggered` state from your security system, that isn't possible either with a real HomeKit accessory.

If you prefer, you can also create a scene where you turn on the virtual switch and Eve Energy if you prefer it simple.
