### ISSUE TITLE
Add switch to temporarily set the mode to disarmed

### ISSUE THREAD

**Issue by Christian-CFP** [MiguelRipoll23/homebridge-securitysystem#34]
First, I am a hoobs user and 2.7.0 it runs quite good right now.

My wish, I do not know if that is quite in the beta right now, but some kind of toggle mode.
e.g. If Night mode is enabled and my door is locked, i need a way to push/set a button to toggle the security system to e.g. "home" for some time (set seconds like the trigger does) and after that time back to Night mode. So I have time to get out and it will be secured after that again.

**Comment by MiguelRipoll23** [comment]
Thanks for the information related to HOOBS.

I suggest these changes:

- Minutes, not seconds: short amounts of time are risky and you may end up accidentally triggering the security system. I won't require 5 minutes at least though, that's up to the user.
- Instead of switching to an specific mode, switch to off: basically disarm the security system temporarily during this period of time. This adds more uses cases like if you forgot something after leaving the house, get it and exit without worrying about the security system, also makes the feature more less specific.

I guess that your use cases are these:

- Taking the trash out
- Opening the door to someone (delivery, family members, neighbors, .etc..)

**Comment by Christian-CFP** [comment]
Yes, you are right.

**Comment by MiguelRipoll23** [comment]
Will get back to you once the feature has been added to the upcoming version.

Thanks for the suggestion.

**Comment by Christian-CFP** [comment]
Awesome! Thank you.

**Comment by MiguelRipoll23** [comment]
Available now on version 2.8.0 🎉

**Note**
When a mode is paused, it will switch temporarily to Off mode and revert back to the original mode once the time indicated by the `pause_minutes` option passes.. You can turn off the `Mode Pause` switch to revert to the original mode immediately.

**Comment by Christian-CFP** [comment]
Awesome, works!
BTW. What is the "reset_minutes"?

**Comment by MiguelRipoll23** [comment]
It’s used to reset the alarm back to the armed mode it was in after waiting the minutes set when the alarm gets triggered.

For example, if mode is set to `Away` and the alarm gets triggered, it waits the minutes set by that option and resets the security system back to `Away`.

**Comment by Christian-CFP** [comment]
Ok, so it is a limitation of "Alarm" is on? e.g. after some minutes switch back to away. And the alarm turnes off, right?

In addition, only for me for understanding the security system inside Homekit.
I had tried to automate it. e.g. If no one is at home set it to "away". And if anyone arrives at home set it to "home". But it does not work.

Does Homekit handle security systems differently? So that I am not able to automate it?

**Comment by MiguelRipoll23** [comment]
Sorry for the delay.

If you’re still talking about `reset_minutes`, it’s basically stopping the “siren” after x minutes and going back to the armed state it was in just like a real alarm.

Yes, you need bypass HomeKit restrictions for location triggers using the `unsafe_mode_switches`.

**Comment by Christian-CFP** [comment]
Thank you for your awesome work!
