### ISSUE TITLE
Ability to move the Trip switches to a different room from the security system

### ISSUE THREAD

**Issue by Olivierbkk** [MiguelRipoll23/homebridge-securitysystem#369]
### What are you missing?

Hello, 

Is it possible to move the Trip switches to a different room from the security system itself? When I move the switches the security system follows.

The reason is to have a clean security system switch in a room I call "General" and the trip switches that should not be touched by anyone in a room I call "System".

Thanks in advance.

**Comment by MiguelRipoll23** [comment]
Hey there,
If you check the accessory settings, you should find an option to ungroup the sub-accessories that are provided by the plugin, does this happen as well with the sub-accessories ungrouped?

**Comment by Olivierbkk** [comment]
Hi,
In the Home app, when I show the trip switches in separate tiles and move those tiles to another room, the security system  tile also moves to that room by itself.
It could be that the switches need to be different devices rather than sub accessories of the SS. It may require an option in the plugin to have the switches as separate devices. No idea how big a job it is... Over to you Miguel :-D

**Comment by MiguelRipoll23** [comment]
Unfortunately it looks to me that it may not be possible due to a Home app limitation for HomeKit accessories that expose multiple accessories like this plugin. Other Homebridge plugins whose expose itself as a platform may evade this limitation but this plugin was designed as a standalone plugin (no need to communicate to a third-party device).
