### ISSUE TITLE
Siren switch optional

### ISSUE THREAD

**Issue by nielsth** [MiguelRipoll23/homebridge-securitysystem#4]
Could the siren switch be made optional? I don't see the use for it since a triggered alarm can be used as a trigger to run a scene or control specific (physical) accessories.

**Comment by MiguelRipoll23** [comment]
Use case of the Siren switch is to trigger it since HomeKit clients can’t do this. I understand that you can use the Home app to automate accessories based on the triggered state but there’s no way to trigger it, you can only change it to a mode.

That’s why there’s a virtual switch to do this. If this were a real securirty system accessory the way it would by triggered would be using the manufacturer’s sensors outside the HomeKit protocol, it’s kinda stupid but this is the way it was done unfortunately.

**Comment by nielsth** [comment]
Thanks, now I get it :) Works like a charm! 

Too bad indeed the extra switch is needed and the Home app lacks the options to use alarm armed state as a condition for automations.

**Comment by MiguelRipoll23** [comment]
Yup :(

It lacks lot of options when talking about conditions, thankfully the Eve app is quite good and simple to create even the most complex ones.

**Comment by MiguelRipoll23** [comment]
Looks like characteristics can be used to trigger the security system without needing to use the switch so this has been implemented and the switch is now optional.
