### ISSUE TITLE
Prevent arming if doors/windows are open

### ISSUE THREAD

**Issue by johnnygeezz** [MiguelRipoll23/homebridge-securitysystem#40]
Preliminary idea. 

When set status, check if devices are ready. 

Example: Set Away. 
Side window not closed. Prompt me that Away mode set but window not closed. 

Traditional security system won’t arm if a window is open. You would need to close it and try to arm again. Or you would have to specifically bypass a device or zone, like skip the open window, to be able to arm. 

Just an idea. Not sure what a feature would be. Just thinking.

**Comment by MiguelRipoll23** [comment]
There’s a HomeKit limitation due to security that doesn’t allow us to communicate to other accessories to get information or events from them.

This means you would have to do this using the Shortcuts app through an scene but it’s a little bit complex and not entirely sure if possible.

Security sometimes limits features.

**Comment by johnnygeezz** [comment]
That's what I thought, but still wanted to bring it up in case you had some ideas on how to approach it.

**Comment by MiguelRipoll23** [comment]
I wanted to provide a way to do this using Shortcuts but couldn't find any, closing this issue for now but I may re-open once iOS adds more features to the Home or Shortcuts app that allows me to do this.

**Comment by scotthmurray** [comment]
+1 for this feature request, should it ever be possible in the future. For what it's worth, here is the use case I have in mind:

When arming the system, having it automatically check the status of various sensors saves me (the human) from manually doing so. This is convenient and reassuring — as if I see the system in an armed state, then I know it's already confirmed I closed all the doors, windows, and so on.

But this also helps ease other, related automations, by simplifying them. For example, say an automation is set to arm the system at 10pm every night if everyone is home. Then "arming the system" includes automatically checking state of doors/windows/etc. In that case, it would be ideal, when the automation is run, to get a notification at 10pm of either:

- confirmation that system is armed, or
- alert that system was _not_ armed, due to x windows/doors being open, or
- prompt to override x windows/doors being open, so please arm the system anyway [y/n]

@johnnygeezz mentioned overrides above. In the last case here, note that a traditional alarm system includes some additional logic and state handling to "override" specific sensors and to remember which sensors can be ignored (until the next disarm and re-arming). For example, I left the master bedroom window open overnight, and I overrode that sensor, so the system is still armed. As such, when I close, then reopen that specific window in the night, the alarm shouldn't be triggered.

I realize I'm just dreaming at this point — this is probably a lot of work, and not even possible at the moment — but now you have my notes, should this ever be relevant.

(Side note: **Thank you** for developing this wonderful piece of software! I have been testing for about a week and am loving the possibilities.)

**Comment by johnnygeezz** [comment]
@scotthmurray The system will still arm if a window is open say without the need to override that device or zone. This is different than how a traditional alarm system would treat it where it would not arm. I haven't found a way to check that all devices are 'closed' before arming in HomeKit. 

My override function was to delay auto arming manually because the dog walker was coming on a given day.

**Comment by MiguelRipoll23** [comment]
I'd like yo give some additional details about this as it's a great feature and it's been around my head for a while trying to find ways to implement it somehow.

**How it needs to be implemented**
- Plugin has a counter: for every window/door the counter is increased and if they're closed decreased. If the counter is greater than zero then arming is blocked.
- User creates automations on the Home app for every door/window sensor to increase/decrease the counter using two different actions.

**The problem**
As switches remains on when activated, they must be immediately turn off by the plugin when activated so other sensors can increase/decrease the counter. If more than one sensor tries to turn on the `Increase counter` switch for example, during the short time the plugin reverts back the switch to `Off` the other sensor would be ignored and the user ends up in a situation where the security system can't be armed anymore.

**The solution**
At the moment, button's cant be virtually pressed from automations (that would simplify this a lot!). so we can try to do this by entering Shortcuts territory. 

Let's say you have you add these automations on the Home/Eve app for a door:

When door opens -> Run shortcut
Shortcut -> Sends a request to `http://homebridge_ip:port/event/open`

When door closes-> Run shortcut
Shortcut -> Sends a request to `http://homebridge_ip:port/event/close`

Then on the plugin handle these requests to increase/decrease the counter so arming is blocked if the counter is greater than zero. Also, maybe we can make advanced behaviors like @scotthmurray says using the Eve app probably.

What do you guys think? I can implement it this way and we can try it in a beta release today to see if it fits our needs or we encounter new limitations.

**Comment by MiguelRipoll23** [comment]
I was testing a very basic implementation of it, looks like HomeKit doesn't allow you cancel a mode change and will return a `No response` that will make the security system unresponsive for ever.

Looks like you will have to actually set the mode requested by the user no matter what and then revert it due to doors/windows being opened, not very fancy and would really weird with the audio announcements...

Hopefully Apple improves this in the future, this is worst than I expected as you can't even block mode changes when you report a fault or that the security system is tampered.

**Comment by MiguelRipoll23** [comment]
I found a trick to cancel the mode change 😃

A new beta release has been published with a prototype of this feature, you can install it executing the command below on your terminal:

> npm install -g homebridge-securitysystem@beta

### How it works
You will have to send a request to the server both to `/open` or `/close` using Shorcuts when a door or window changes their state, this will increase/decrease the counter from the plugin. If you want to ignore a window/door during night for example, create a Shorcut than runs when night mode is selected that checks if the door/window is opened and if it is, send a request to decrease the counter so the mode can be changed to `Night`.

### Known issues
- During arming, the mode will be changed anyways even if requests to `/open` are received.

### Feedback
Please provide any feedback about this, this is only way I could find to implement it.

Thank you.

**Comment by scotthmurray** [comment]
@johnnygeezz Thank you! I misinterpreted your original use case for a different sort of "override". Thanks for clarifying. I would benefit from your particular sort of override, too!

@MiguelRipoll23 You are awesome for looking into this! For what it's worth, I'm sorry that Apple doesn't expose the needed mechanisms to do this properly yet. For stability and reliability, I always favor jumping through as few hoops as possible — in this case, maybe that means waiting until the needed functionality is fully supported, without relying on "shortcuts".

One idea: Would it help matters at all if the window/door sensors being used lived "inside" HomeBridge? That is, do you get any more control over HomeBridge-managed switches and devices, as opposed to "normal" HomeKit sensors?

**Comment by MiguelRipoll23** [comment]
@scotthmurray I share the same opinion as you, if I can I will always direct the user to HomeKit automations over anything else. I'll always to try to fill gaps the best way I can, lot of stuff has been added to the plugin by users suggesting "out of bounds" features and sometimes the implementation ends up being perfect.  In this case, this invades Shotcuts territory and it's far from perfect unfortunately. 

I wish that Apple improves this aspect once they're done with the most requested features.

> Do you get any more control over HomeBridge-managed switches and devices, as opposed to "normal" HomeKit sensors?

Definitely, plugins like [homebridge-websocket](homebridge-websocket) create a "Hub" that allows us to get or change the state of another Homebridge accessory by sending messages to it. I'd communicate to that Hub from the plugin to interact to other accessories, obviously this is a little bit of a security nightmare though as a malicious plugin could do anything.

This is kinda what real accessories do but privately, sometimes HomeKit accessories have their own sensors from the manufacturer itself and they're communicating outside the HomeKit protocol to add these features that with with just HomeKit wouldn't be able to be integrated.

**Comment by scotthmurray** [comment]
@MiguelRipoll23 `homebridge-websocket` is great to know about. Thank you!

The possibilities with HomeBridge are super exciting. I'll keep my 🤞 that Apple will open up some more cross-device capabilities in HomeKit soon.

**Comment by Karrypto** [comment]
I just stumbled upon this post and wanted to share my thoughts on it.
I already use a simple rule that prevents me from arming the security system when any window is open. It works quite well. Unfortunately without notification ("hey!! window is open !"), but I think one can expect a certain intelligence and conclusion from the user. 😄 

So here is my simple rule for that:

Starting with Eve App:

Trigger: other value -> select **"Security System Arming"** Sensor -> Enable it an set to ON

Condition: select a window or door sensor and set it to IS OPEN

Action: select any scene (unfortunately the Eve App only allows Scenes...so select any scene...it will be deleted in next step)

Go to Home App and edit the rule:

Now remove the scene selected in Eve App before and then select the **"Mode Off"** switch of the security system and set it to ON (Mode Off switch must be enabled in config)

Ready. Now if you try to set the security system to "away" and the window is open, it will not be enabled and the switch moves immediately back to off position. 👍 

Unfortunately the Eve App don't allow to select multiple window sensors for the condition part. You can select them, but then unfortunately ALL conditions (window sensors) must be true for the rule to be executed. Therefore you have to add a rule for every window which should be checked.

A workaround would be variable/switch, which is true/activated if any window is open...like a "Not Ready to Arm" Switch. Then you can use this switch as condition instead of all the window sensors. You can create a rule in Eve App 

Trigger: select every window sensor and set it to IS OPEN
(every trigger will execute the rule)

Action: set "Not Ready to Arm" switch to ON

Now we can use the first rule with this "not Ready to Arm" switch as condition and it should work like a charm 😃 

I know...this is one more virtual switch to implement *arrrg* 🙅 , but this would be an easy solution. Of course, you can also use a light bulb or something else you already have for this variable...but that's kind of bad too 🤔 

I know it's not as complex as the original idea in this post, but it certainly helps to use the basic idea first. What you think.

**Comment by scotthmurray** [comment]
@Karrypto Wow, that is _quite_ the workaround. 😉

**Comment by MiguelRipoll23** [comment]
@Karrypto''s idea of a virtual switch to lock arming when set to Away mode could work, I thought that HomeKit would prevent duplicated turn of/off commands (multiple doors/windows) but actually they are sent. So I added a counter to the plugin and turning on/off this switch will increase/decrease the count.

Apparently it's working great! The only downside is that you to need to create two automations per contact sensor (one that turns on the switch to increase the count and another that turns it off to decrease the count).

If anybody here would like to try it out install the latest beta, enable the option `Show Arming Lock Switch` under the switches section and then create an automation that turns on the `Arming Lock` switch when a door/window is opened and another one that turns it off when it gets closed.

`npm install -g homebridge-securitysystem@beta`

If it works nice for everyone maybe we can release this feature 🙂

**Comment by MiguelRipoll23** [comment]
Feature is now in the stable channel, still marked as beta though 😉

**Comment by Karrypto** [comment]
Hi Miguel, I just read your comment and I want to share my thoughts on this.
I think the idea with the counter is actually quite good, but I don't think it will be practical and stable enough in the long run.
My idea was to use the switch only as a dummy variable (with no intelligence behind) just to "group" the different window & door sensors for creating the rule. I wouldn't make the whole thing too complex, because it really depends on creating the rules correctly, because that's where all the intelligence lies.

As I already mentioned, the Eve App only allows multiple window sensors for the condition part, if ALL these conditions (window sensors) are true (open). Only then the rule will be executed. Therefore, my workaround was this virtual switch, so that only one condition and one rule is necessary.

In order to use the whole thing without an additional virtual switch, you could convert the rule action into Siri Shortcuts while creating the rule in the Home app and then manually script all the sensors with "if-then". But I guess this might get too complex for some too.

The best and easiest way to do it is to create the rule with the App "[Home+ 5](https://apps.apple.com/de/app/home-5/id995994352)" from "Matthias Hochgatterer". This App perfectly allows to create the rule in one step, because here you can change the condition part from "ALL conditions must be met" -> to "only ONE of the added conditions must be met" to execute the rule. This is exactly what we want. We add all the window & door sensors as a condition and as soon as one of these sensor is open while the system is arming, the rule is triggered and the security system will be switched off.

That's actually the best solution for the moment I guess. Hopefully Apple will soon expand the options for creating these kind of rules via Home App so that third-party apps are no longer required for that.

**Comment by MiguelRipoll23** [comment]
Thanks @Karrypto,very well thought!

> We add all the window & door sensors as a condition and as soon as one of these sensor is open while the system is arming, the rule is triggered and the security system will be switched off.

This could disable the security system right when you open the door to exit although I like the idea that the doors/windows should remain closed _while arming_ (instead of checking if they're closed at the most you arm it).

Right now the implementation of this can work as a simple boolean true/false or a counter. The counter is kinda optional and while it worked great during testing I expect out￼-of-sync issues 😅
