### ISSUE TITLE
Get system status in Shortcuts 

### ISSUE THREAD

**Issue by blancjerome** [MiguelRipoll23/homebridge-securitysystem#41]
I can't make a script in Shortcuts app to get automations with conditions. 

As an exemple, I would like to check every morning if the night mode is set and if I'm detected, disable it. To do so, I have to get the status of the system and make a test (If/then/Else) on its value.

When writing the script, I can only define status as integer value, so I tried to test values like "1" or "0". Unfortunately, when running the script, I am told that string result can't be converted to integer. I seems that the returned value for the system status is a string ("home", "away", "nigth" ...).

Can you fix this by allowing defining string values in the script or by returning integer values while it is executed ?

To test, just make an automation and ask to convert it to a shortcut, then try to make a rule that tests the system status.

Thanks in advanced for your help.

Regard,

Jerome

**Comment by MiguelRipoll23** [comment]
Sorry for not answering sooner, I had to take a rest yesterday due to bad sleep. Security’s  system modes are a number internally:

```
static readonly STAY_ARM = 0;
static readonly AWAY_ARM = 1;
static readonly NIGHT_ARM = 2;
static readonly DISARMED = 3;
static readonly ALARM_TRIGGERED = 4;
```

The thing is, this is part of the HomeKit accessory protocol so it can’t be changed. My HomeKit Hub is on iOS 12 so I can’t create advanced Home automations to see what’s happening, nice to see that you solved the issue then 🙂
