### ISSUE TITLE
audio warnings via sonos

### ISSUE THREAD

**Issue by Karrypto** [MiguelRipoll23/homebridge-securitysystem#42]
Hey Miguel, glad to see how this project moved forward since I opened the very first issues :) ...if you remember ;)

Unfortunately I don't have a HomePod or Airplay 2 device to use the new audio feature, but Sonos speakers in every room. Maybe you could also implement audio output on Sonos as an alternative. I am currently using this API (https://github.com/jishi/node-sonos-http-api) with OpenHAB for various notifications. You can trigger an audio file (or dynamic TTS) on all speakers at the same time with a simple HTTP invoke. Works great for years now.

This would be great and quite easy to implement I guess.

**Comment by MiguelRipoll23** [comment]
Hello, yup I remember the first Issues! 🙂

I’m very happy with the newly released audio feature because it brings back something I removed, due to a really bad implementation, from the original idea.

This audio feature doesn’t require AirPlay 2 though, it works using a wired speaker on the same device. What are you suggesting I think it’s possible to do using the command options but I do need to do some research first so I can confirm it and help you too if necessary.

I’ll get back to you tomorrow with with my findings.

P.S. thank you so much for your very firsts issues, it helped me out to make this plugin way better that I originally planned. I really appreciate it, for real.

**Comment by MiguelRipoll23** [comment]
That API is amazingly friendly, I love it.

You can eve use call it using Webhooks:

```
"webhook_url": "http://locahost:5005"
"webhook_target_away": "/sayall/Arming security system to Away mode/en-us"
"webhook_current_away": "/sayall/Security system armed to Away mode/en-us"
"webhook_triggered": "/clipall/clip/alarm_sound.mp3"
```

The more advanced method is still easy too:

`curl http://locahost:5005/sayall/Arming security system to Away mode/en-us`

Is this what are you doing right now or you're just using it with OpenHAB?

**Comment by Karrypto** [comment]
Yes, that's exactly how I use it. OpenHAB simply use the curl command method with a rule generated string/url for my notifications. :) now we just have to marry it with your plugin somehow ;)

**Comment by Karrypto** [comment]
sorry, seems I'm ready for a vacation ^.^ ... I can already use webhooks -.- ... totally missed this point...that's of course the easiest way :)

**Comment by MiguelRipoll23** [comment]
Haha, that's okay!

I was reading again this post meanwhile and I was about to ask you how does your rules look and how the integrations that you have are working with Sonos to see how OpenHAB worked.

I saw a little bit about it some time ago and it looked like Shortcuts but coding (which is pretty nice!), if there's anything I can improve or answer you be free to continue the discussion here :)
