### ISSUE TITLE
webhook request not sent with config.webhook_current_off

### ISSUE THREAD

**Issue by funkyremi** [MiguelRipoll23/homebridge-securitysystem#49]
Since the latest version, the webhook request is not sent for config.webhook_current_off

**Comment by MiguelRipoll23** [comment]
Sorry, thanks for noticing.

The call was ignored due to some old behavior that wasn't removed correctly.

I just released a beta release with this issue fixed, it will be released to the general public as soon as tomorrow. You can install the beta update to solve this issue using the following command:

`npm install -g homebridge-securitysystem@beta`

**IMPORTANT:** If you're a HOOBS user, please wait until the beta phrase has ended. 

Remember that you can leave the beta program anytime using the command below:

`npm install -g homebridge-securitysystem@latest`

Thanks!

**Comment by raixer** [comment]
When I installed it, it replaced my custom sound.

**Comment by MiguelRipoll23** [comment]
@raixer custom sounds are new files created by you, you mean deleted?

**Comment by raixer** [comment]
I just made a copy of the current-triggered.mp3 and named it current-triggered-custom.mp3
When I installed the new version it is like it practically deletes everything and installs it anew.

**Comment by raixer** [comment]
should I be doing npm update instead of npm install?

**Comment by MiguelRipoll23** [comment]
It looks like is doing a clean install then, I think the update behavior is very similar and the same will happen.

I'll add an option or replace the existing one for one that you can provide a path to a directory with sounds (that lives outside the plugin) so this won't happen.

I got some free time as I'm on vacation, will fix this ASAP.

Apologies for the inconvenience!

**Comment by MiguelRipoll23** [comment]
New stable update just released with the bug encountered fixed, you can now update the plugin using the Homebridge / HOOBS UI.

The audio issues will be fixed in a future update that will arrive this week.
