### ISSUE TITLE
Alarm Sounds Question

### ISSUE THREAD

**Issue by clipse2004** [MiguelRipoll23/homebridge-securitysystem#58]
Hello Miguel, 

i dont understand how i can use a arming sound. In the GUI i set the path for the audio file and installed ffmpeg.
But the sound dont come up when i arming the security system :/

*update*:
Ah now it shows me up, but i dont hear anything:
14.8.2020, 19:30:33 [Security System] Target mode (Off)
14.8.2020, 19:30:33 [Security System] Current mode (Off)
14.8.2020, 19:30:33 [Security System] /home/hoobs/.hoobs/node_modules/homebridge-securitysystem/sounds/en-US/en-US/current-off.mp3

can you explain me, how i connect my homepods over airplay with my raspberry?

thanks for your help

**Comment by MiguelRipoll23** [comment]
Hello!

In order to play sounds with AirPlay you need to use the Home app and create automations with it for each sound you would like to play because at this time, we (plugin developers) can't make use of AirPlay as Apple keeps it private. The plugin has an audio feature that works only with speakers connected to your Homebridge device (without using AirPlay) which is the one that you're using but won't accomplish your goal.

[I made this quick guide](https://github.com/MiguelRipoll23/homebridge-securitysystem/wiki/Playing-audio-with-AirPlay-2) to play sounds with AirPlay, all you need is a Homebridge Hub and a AirPlay 2 speaker. If you want to use custom sounds you would need to import them to your iTunes library.

**Comment by clipse2004** [comment]
Ah thanks now I’m understand!
