### ISSUE TITLE
"mode away switch" not switchable

### ISSUE THREAD

**Issue by Karrypto** [MiguelRipoll23/homebridge-securitysystem#76]
Hi Miguel, seems the "mode away" switch is currently not responding to inputs. I use this switch to disable the security system when coming home via geo and to bypass conformation. Unfortunately it's not working anymore. I also tested it with a simple NFC automation, same issue. You even can't turn off the switch manually via Home app.

**Comment by MiguelRipoll23** [comment]
Hello!

This was a change introduced due to #64 starting from [v3.4.1](https://github.com/MiguelRipoll23/homebridge-securitysystem/releases/tag/v3.4.1), in order to avoid issues with automations when a mode switch is turned off a no response error is sent.

The mode switches can't be turned off manually, it will happen automatically when switching modes.

My recommendation would be to use the mode off switch for this, if there is a preference to avoid using this switch maybe we can find another alternative?

Thank you :)

**Comment by Karrypto** [comment]
Hey, thanks for pointing this out...I better should read the change log in detail 😅

Ahhh, so I can still use the mode switches for automations to activate modes. OK, otherwise the switches doesn’t make really sense 😄 

I will use the mode off switch for my „disarm“ automation now...I’m fully ok with that 👍 
No need to create more virtual switches 🙅 😃 

Thanks

**Comment by macjl** [comment]
Hello,

To be clear, my problem in issue #64 was that was my automations changed the state of the alarm when switching an button that was already in target state. I'll try to be clear with this table : 

Before 3.4.1
Alarm State|Mode Away Switch State|Mode Night Switch State|Action made by automation| Result | Expected Result| Status
------------|---------------------------|----------------------------|-------------------------------|--------|-----------|--
Night Mode|Off                                | On                                   | Switch off Mode Away Switch | Alarm set to off | No action|❌
Away Mode|On                                | Off                                    | Switch off Mode Away Switch | Alarm set to off | Alarm set to off | ✅

After 3.4.1
Alarm State|Mode Away Switch State|Mode Night Switch State|Action made by automation| Result | Expected Result|Status
------------|---------------------------|----------------------------|-------------------------------|--------|-----------|---
Night Mode|Off                                | On                                   | Switch off Mode Away Switch | No action | No action| ✅
Away Mode|On                                | Off                                    | Switch off Mode Away Switch | No action | Alarm set to off | ❌


Could it be possible to have a version that covers both cases?

**Comment by Karrypto** [comment]
Hmm..I understand the behavior and what’s your problem seems to be here, but I can’t fully imagine what’s your idea behind this ? Maybe you can explain what you want to achieve..I mean the rule idea behind this. It's sometimes easier to think a rule in another way instead of creating crazy rule conditions.

**Comment by MiguelRipoll23** [comment]
By the way, the modes switches turn off automatically when another mode switch is turned on, they also are synchronized.

I don't fully understand why you're turning them off, you seem to be expecting different results when a mode switch is turned off depending of their mode.

Can you please describe your use case?

The change implemented has some benefits like preventing mode changes due to generic "turn of" phrases made to Siri or accidental control center presses.

I will have some free time on December and I really want to improve this plugin as much I can internally (organizing code, improving past decisions) so any change can be discussed and implemented in a better way if needed.

**Comment by macjl** [comment]
Hello,

Try to explain mu usage : 

## Automations : 
#### Automation 1
Alarm state : Away mode
Trigger : Someone detected in the home with a presence sensor, but there should be nobody.
Action : Activate 'Siren Switch' to set alarm in trigger mode

#### Automation 2
Alarm state : Night mode
Trigger : Someone detected in the home with a presence sensor, because someone is awake in home.
Action : Deactivate 'Night mode switch' to deactivate alarm

#### Automation 3
Alarm state : Away mode
Trigger : Member of family arrives at home
Action : Deactivate 'Away mode switch', to deactivate alarm

## WAF
My wife wants to have less possible switches in the alarm device. She doesn't understand why the status is "Powered On" when the alarm is deactivated. It's due to the 'Mode Off' switch that's on. So I prefer too hide this switch.
![Screenshot 2020-11-14 at 19 22 29](https://user-images.githubusercontent.com/19387619/99154578-3f6b5e00-26b1-11eb-969c-3d5a96c14a36.png)

## Problem with versions  prior to 3.4.1 :  
When an intruder was detected in the home when mode is away, both automation 1 and 2 are triggered. The automation 2 set the switch 'Night mode' to off, even if it was already in that state. Then, the alarm deactivate, and the alarm doesn't do anything. So the intruder can continue steeling things in my home without problems.

## Problem with versions after 3.4.1 : 
When someone of the family gets home, automation 3 is activated. The 'Mode Away' switch is set to off. But nothing happens. So when he opens the door, the alarm triggers.
Workaround : display the 'Mode off' switch, and change the automation 3 to set it to On on the automation 3. But then, wife is not happy, because of the icon displaying 'Powered On' when alarm is deactivated.


Hope I've been clear enough with my little problems! This homebridge plug-in works very good, and the problem I have are juste little things that doesn't affect my love to that plug-in.

**Comment by Karrypto** [comment]
@macjl I don’t really understand your Night automation use case. It’s also a alarm mode...it’s to secure rooms you don’t normally walk through at night...so if someone is detected there, you should trigger the alarm, but not deactivate it. You can only use Away or Night mode...not both at the same...so sorry I’m a bit confused 🤔 

But as a quick solution I would suggest you to show all alarm switches as separate tiles. This is an option in the Home App. Open the settings of the Security device and klick „Show as Separate Tiles“ . Then all the mode switches and also the mode off switch is shown as a separate tile. Now your Security device shows only the modes available. Very user friendly for your wife 😄  I have it the same. ( I also moved all the switches related to the Alarm to a separate room only for this and you have a better overview to all the switches. ) Now you can use the mode off switch for your automations and the alarm icon is really showing power off when alarm is deactivated. 

Hope this helps you out 🤞

**Comment by macjl** [comment]
Hello @Karrypto !
In my home, the night mode is just monitoring external sensors of my house. You can freely move between rooms without problems, but if you open a door or the garage, it will trigger the alarm. 
The deactivation automation is only active on the morning, to deactivate the alarm when first person comes in living room. With this automation, we avoid forgetting to disable the alarm and open a door that will activate the 🚨. 

For your workaround, it’s a good idea. Thank you, I’ll try it.
