### ISSUE TITLE
How to model door/window state?

### ISSUE THREAD

**Issue by larsxschneider** [MiguelRipoll23/homebridge-securitysystem#96]
👋 Hi,

I have a non-homekit compatible Alarm system and I try to use this project to bridge it into HomeKit. Modeling the general state of the alarm system works - thank you 🙇 ☺️ !

My Alarm system also reports the state of my doors/windows and I would also like to see that in HomeKit as well. Is there a recommended way to achieve that with this project or is that out of scope?

**Comment by MiguelRipoll23** [comment]
I wanted to even provide a native functionality of this but I was way too limited by HomeKit.

What would you need to make this possible? A switch that blocks arming right?

**Comment by larsxschneider** [comment]
> What would you need to make this possible? A switch that blocks arming right?

No, my alarm system would not get successfully into "armed mode" if any door/window is open. I just wonder if it would be possible to show somehow open doors/windows in HomeKit. I imagine to poll my alarm system every minute or so for the state of every door/window and then I would like to visualize that in HomeKit.

If you feel that this kind of functionality would fit into your project, then I would be happy to take a stab and provide a PR. I know my ways around JS. I just would need some hints how to implement in the most suitable way.

**Comment by ashpole** [comment]
Is using IFTTT as the bridge between the alarm system and Miguel’s plug-in?

**Comment by MiguelRipoll23** [comment]
@larsxschneider when I discussed this in #40 the way I wanted to implement it was like this:

The plugin has an internal counter (an obstructions count) and a HomeKit switch to increase/decrease this count is exposed. Trying to turn on the switch multiple times? The internal count gets increased. If you turn it off instead, the counts gets decreased until it hits zero. If this number is above zero, trying to arm the security system gets ignored and HomeKit reverts it to the current mode. There would be also server endpoints to increase/decrease this count (when acting like a proxy, like your case).

When I discussed this I didn't have time to investigate if duplicate turn on/off actions were allowed by HomeKit, I just checked now and they're allowed. How would you feel about this, will it work for you?

Showing the doors/windows accessories using the plugin may be a little bit out of scope, the codebase it's getting bigger due to the flexibility of the plugin and there's an ongoing migration to TypeScript that I'm working on that will happen sometime in the future 🙂

**Comment by MiguelRipoll23** [comment]
I missed the most important part in my explanation: this requires an automation for each door/window that will turn on or off according to the event that happened (opened or closed).
