### ISSUE TITLE
Activating away mode with block switch on causes not responding error

### ISSUE THREAD

**Issue by CooperCGN** [MiguelRipoll23/homebridge-securitysystem#99]
**Describe the bug**

In the Home app when trying to activate away mode manually with the new block switch set to on security system shows a not responding error until opening the app again.

**To Reproduce**
see above

![33C70906-5055-4D50-98B5-0BD7EEAF0828](https://user-images.githubusercontent.com/29116509/114259998-657ffa80-99d2-11eb-8176-f9d45c73103c.jpeg)

**Comment by 0ldF0x** [comment]
I've noticed the same issues sometimes when I enable away mode. 
I've recently updated the plugin from the much older version, which by the way worked smooth, without any "not responding" errors. @MiguelRipoll23 You're doing good job with all the support, but maybe this plugin is getting "too heavy" and needs some refactoring...

**Comment by MiguelRipoll23** [comment]
Hey there,

This is intended behavior, let me explain.

This new `Arming Lock` switch blocks arming when set to Away, in order to cancel the arming by the user, the plugins sends to HomeKit an error response. Apple for the sake of simplicity shows the user a `No response` error, which was and still is a good idea as the kind of logic this plugin does is outside Apple native functionality for security systems.

There's a thing though, in the release notes I wrote that this switch is to block arming when doors/windows are opened and may imply that it does it automatically **which it's not possible** (you need to create automations when a door/window is opened which turn this new switch on). **This part from the release notes has already been removed to clarify.** This new `Arming Lock` switch also has an internal counter, which means you can turn it on multiple times (while still on) to provide support for multiple "obstructions" that should work arming. Even if this new switch is off and that counter is above zero, it will block the arming request.

**Comment by MiguelRipoll23** [comment]
@0ldF0x you said you noticed some issues when setting the Away mode, was using this new feature? If you can can give me any other information to reproduce I appreciate it, Will investigate, so sorry about that.

**About the future of the plugin:** I totally understand your worries about the codebase, the code itself is pretty good but is just part of one single file. I should talk (and will publish a discussion today) more openly about the migration to TypeScript that I'm doing and the reason of which it's taking so long. In brief words the migration is currently paused as it's still not worth it until Homebridge continues to evolve (some APIs were [just introduced recently](https://github.com/homebridge/HAP-NodeJS/projects/4#card-46791216) and [some ones were postponed.](https://github.com/homebridge/HAP-NodeJS/projects/4#card-37782559)

Once the Homebridge library is fully evolved and has reached almost all of its users, rest assured that the migration will continue and the codebase will be flawless. They're doing amazing work, they already implemented promises and better error responses which I'd like to use in the code but I can't (users would need to be in the latest version).

**Comment by 0ldF0x** [comment]
> @0ldF0x you said you noticed some issues when setting the Away mode, was using this new feature? If you can give me any other information to reproduce I appreciate it, Will investigate, so sorry about that.

No, I didn't even know about that new feature. I don't use it.
Actually I think that the issue in my case was "arm_seconds", which was set to 5s - this is probably why the homekit returned the "no response" error. Now I've changed it to 1s and I think it's better. I'll open the new issue if I manage to reproduce the problem.

Otherwise good job. Can't wait for the TypeScript migration :)

**Comment by MiguelRipoll23** [comment]
@0ldF0x [just created a discussion](https://github.com/MiguelRipoll23/homebridge-securitysystem/discussions/100) to follow the status of the migration, will keep it updated.
I'll be more open from now on.

I'm gonna investigate what could be happening, you shouldn't experience issues setting it to five seconds 😟

**Comment by 0ldF0x** [comment]
Great, thanks!

**Comment by CooperCGN** [comment]
I was well aware that I have to create some automations by myself to utilize that switch like when opening a window set it to on and when all windows are closed turn it off. What I don’t get is the counter you mention. What if this gets out of sync for some reason, how do I set it to zero then?

**Comment by MiguelRipoll23** [comment]
If it gets out of sync, create an scene that turns it Off tap on `Test This Scene`. You will see `Arming Lock (-)` indicating that the counter has been decreased. It's a still a beta feature, we'll see what can be improved along the way.

**Comment by CooperCGN** [comment]
Still I don’t get the idea behind the counter. It takes two automations to make it properly being set to on and off which you have to create anyway. One where all windows are set as triggers when being opened to turn it on and another one with all windows as triggers and all windows being closed as condition to set it to off. All you have to do is set up those automations in an app like eve or controller for HomeKit. That „tap a scene“ to reset it to zero in case of desync sounds user unfriendly to me.

**Comment by MiguelRipoll23** [comment]
After the feedback gathered, the behavior has been changed in the beta channel. I'm gonna close this issue and we'll moving the discussion to #40.

The implemention of the feature may still vary while still in beta.
